export const lib1 = `Lorem Ipsum
"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas semper gravida est eget varius. Curabitur in pharetra erat, sit amet maximus nunc. Maecenas vel leo ut turpis eleifend maximus. Aenean dictum ante vitae tincidunt iaculis. In hac habitasse platea dictumst. Cras vitae dapibus neque, at elementum lectus. Etiam eget porttitor nibh.

Integer eu nulla sed nisi placerat tempus et sit amet est. Donec molestie felis sed sodales commodo. Maecenas ac dignissim ipsum, lobortis tristique risus. Vestibulum lobortis maximus nibh vel rutrum. Vivamus interdum rhoncus nisl. Vestibulum vestibulum quam quis nibh egestas, eget placerat tortor consectetur. Donec non sem lacus. Donec quis ligula sit amet arcu consequat fermentum. Cras pulvinar scelerisque lectus, nec gravida nulla sodales at.

Cras egestas varius tincidunt. Nam vehicula, sem vel molestie porttitor, augue neque auctor quam, sit amet aliquet magna arcu ac sem. Nunc convallis sollicitudin justo nec tristique. In id lectus sit amet eros congue gravida. Morbi lorem orci, congue ac ex ut, gravida volutpat erat. Phasellus vitae elementum tellus. Quisque sed sollicitudin mauris. Quisque vitae ullamcorper neque. In hac habitasse platea dictumst. Nam tempus sollicitudin lorem vitae placerat. Ut sed massa urna. Ut semper magna nec bibendum dignissim. Cras ultrices nulla leo, at bibendum massa dictum sit amet.

Donec luctus neque nunc, non dictum lacus rutrum ut. Sed pulvinar blandit sapien, eu laoreet tellus tincidunt vel. Sed lectus purus, porttitor eu pharetra eget, sollicitudin in magna. Integer dictum, dolor eu mattis semper, sem nisl ornare arcu, vitae porttitor ligula lectus et nunc. Donec sit amet nisl commodo, interdum lectus id, placerat dui. Etiam maximus ante ante. Donec rutrum dignissim ultricies. Proin aliquam quam vitae leo placerat ultricies. Aliquam erat volutpat.

Vivamus neque nisi, rhoncus ut laoreet vel, ultricies non lorem. Mauris vel odio hendrerit, rutrum diam sit amet, commodo tortor. In hac habitasse platea dictumst. Vivamus consectetur tempus ipsum, id pulvinar quam facilisis sit amet. Sed sed metus odio. Cras id cursus lacus, pretium vehicula orci. Cras tortor leo, maximus non ipsum ultricies, elementum mattis orci. In vitae gravida diam. Proin tempor ex et semper vulputate. Fusce ut blandit ante. Nam et elementum enim, sed sodales diam. Aenean feugiat velit tellus, id dignissim sapien blandit et. Praesent vehicula lacus nec accumsan feugiat. Aenean pulvinar nisi risus, ac imperdiet dolor lacinia fermentum. Mauris et lectus vulputate, pharetra augue a, convallis velit.`